name: Build and publish snapshot on develop
run-name: Build and publish snapshot on develop
on:
  push:
    branches:
      - develop
      - github-actions

jobs:
  Build-snapshot-develop:
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'release-update' }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Run the Maven build
        env:
          FOP_SIGN_GPG_KEY: ${{ secrets.FOP_SIGN_GPG_KEY }}
          FOP_SIGN_GPG_PASS: ${{ secrets.FOP_SIGN_GPG_PASS }}
        run: mvn clean deploy --file pom.xml --batch-mode --settings settings.xml --activate-profiles ci
