name: Release from master
run-name: Release from master

on:
  push:
    branch: master

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Git config setup
        run: |
          git config user.email "github-action@users.noreply.github.com"
          git config user.name "GitHub Action"
          git config user.password "${{ secrets.FOP_RELEASE }}"
          echo "GIT_USER=${{ github.actor }}:${{ secrets.FOP_RELEASE }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.FOP_RELEASE }}" >> $GITHUB_ENV

      - name: Checkout branch master
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Find release version
        run: |
#          mvn build-helper:parse-version versions:set@release --settings settings.xml
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_ENV"

      - name: Prepare a release branch
        run: |
          git checkout -b release/$version
          git add -A
          git commit -m "release version $version"
          git push --force origin release/$version

      - name: Build and publish to maven central
      - run: |
          mvn clean deploy --file pom.xml --batch-mode --settings settings.xml --activate-profiles ci

      - name: Merge back to master from release branch
      - run: |
          git checkout master
          git merge release/$version --commit
          git push --force origin master
          

      - name: Tag the release
        run: |
          git tag -a v$version -m "release version $version"
          git push --force origin v$version

      - name: Create a Github release from tag
      - run: |
          gh release create v$version --verify-tag --notes "Release version $version"
          
          
