name: Testing
run-name: Testing

on:
  push:
    branches:
      - github-actions

jobs:
  Release:
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message == 'testing-update' }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event with commit message ${{ github.event.head_commit.message }}."