name: Testing
run-name: Testing

on:
  push:
    branch: github-actions

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting to increment ${{ github.event.inputs.versionIncrementType }} version"
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Checkout
        uses: actions/checkout@v4

      - name: Git config setup
        run: |
          git config user.email "github-action@users.noreply.github.com"
          git config user.name "GitHub Action"
          git config user.password "${{ secrets.GITHUB_TOKEN }}"
          echo "GIT_USER=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Testing git commit back to same branch
        run: |
          touch testing.txt
          git add -A
          git commit -m "testing"
          git push