name: Version increment
run-name: Versioning
on:
  push:
    branches:
      - 'github-actions'
  workflow_dispatch:
    inputs:
      versionIncrementType:
        description: Version to increment
        options:
          - patch
          - minor
          - major
        required: true
        default: patch

jobs:
  Versioning:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting to increment ${{ github.event.inputs.versionIncrementType }} version"
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - uses: actions/checkout@v4
        with:
          ref: 'develop'
      - run: mvn build-helper:parse-version versions:set@${{ github.event.inputs.versionIncrementType }}
      - run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_ENV"
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git checkout -b version/$version
          git add -A
          git commit -m "increment version"
          git push origin version/$version
          gh pr create --base develop --title "version increment by Github action" --body "version increment" --reviewer funofprograming

